before_install:
  chmod +x install-pebble-sdk.sh
  chmod +x install-pebble-sdk-2.sh
  chmod +x build.sh
  ./install-pebble-sdk.sh
  export PATH=$PATH:$PWD/pebble-sdk-4.5-linux64/bin/
  ./install-pebble-sdk-2.sh

script: ./build.sh
